 - hosts: masternode
   vars_prompt:
    - name: master_ip
      prompt: "Enter Ip of master node "
      private: no
   
    - name: m_node
      prompt: "Enter directory name for master node "
      private: no
   vars: 
    folder: '{{m_node}}'
   tasks:
   - name: "copy hadoop .rpm file"
     copy:
      src: "/root/Downloads/hadoop-1.2.1-1.x86_64.rpm"
      dest: "/root/"
   - name: "copy jdk file"
     copy:
      dest: "/root/"
      src: "/root/Downloads/jdk-8u171-linux-x64.rpm"
   - name: "installation of jdk"
     yum:
      name: "/root/jdk-8u171-linux-x64.rpm"
      state: present

   - name: "installation of hadoop"
     command: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
   
   - name: "creation of directory in masterode"
     file:
      path: "/{{folder}}"
      state: directory

   - name: "configuration of core-site.xml file for masternode"
     template:
      src: "/root/core-site.xml"
      dest: "/etc/hadoop/core-site.xml"

   - name: "configuration of hdfs-site.xml file for masternode"
     template:
      src: "/root/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"
         
   - name: "Firewall setting for masternode"
     firewalld:
      port: 9001/tcp
      permanent: yes
      state: enabled

   - name: "start masternode service"
     command: "hadoop-daemon.sh start namenode" 
      

   
 - hosts: datanode
   vars_prompt:
    - name: master_ip
      prompt: "Enter Ip of master node "
      private: no
    - name: d_node
      prompt: "Enter directory name for datanode node "
      private: no
   vars:
    folder: '{{d_node}}'
   tasks:
   - name: "copy hadoop .rpm file"
     copy:
      dest: "/root/"
      src: "/root/Downloads/hadoop-1.2.1-1.x86_64.rpm"
   - name: "copy jdk file"
     copy:
      dest: "/root/"
      src: "/root/Downloads/jdk-8u171-linux-x64.rpm"

   - name: "installation of jdk"
     yum:
      name: "/root/jdk-8u171-linux-x64.rpm"
      state: present

   - name: "installation of hadoop"
     command: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
     
   - name: "creation of directory in datanode"
     file:
      path: "/{{folder}}"
      state: directory

   - name: "configuration of core-site.xml file for datanode"
     template:
      src: "/root/core-site.xml"
      dest: "/etc/hadoop/core-site.xml"
   
   - name: "configuration of hdfs-site.xml file for datanode"
     template:
      src: "/root/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

   - name: "start datanode service"
     command: "hadoop-daemon.sh start datanode" 

       
   
       
